"""Render an RCAReport (+ its evidence bundle) as a Markdown incident report."""
from __future__ import annotations

from datetime import UTC, datetime

from agent.models import RCAReport, SignalBundle


def render_markdown(bundle: SignalBundle, rca: RCAReport) -> str:
    now = datetime.now(UTC).strftime("%Y-%m-%d %H:%M:%SZ")
    lines: list[str] = []
    a = lines.append

    a(f"# RCA — {rca.title}")
    a("")
    a("| Field | Value |")
    a("|---|---|")
    a(f"| Service | `{rca.affected_service}` |")
    a(f"| Severity | **{rca.severity.value}** |")
    a(f"| Confidence | {rca.confidence.value} |")
    a(f"| Generated | {now} |")
    a(f"| Evidence window | {bundle.window_minutes} min |")
    a("")

    a("## Summary")
    a(rca.summary)
    a("")

    a("## Symptom")
    a(rca.symptom)
    a("")

    a("## Root cause")
    a(rca.root_cause)
    a("")

    a("## Evidence")
    for e in rca.evidence:
        a(f"- {e}")
    a("")

    if rca.contributing_factors:
        a("## Contributing factors")
        for c in rca.contributing_factors:
            a(f"- {c}")
        a("")

    a("## Remediation")
    for i, step in enumerate(rca.remediation, 1):
        a(f"{i}. **[{step.urgency}]** {step.action}")
        a(f"   - _why:_ {step.rationale}")
    a("")

    if rca.prevention:
        a("## Prevention (Day-2)")
        for p in rca.prevention:
            a(f"- {p}")
        a("")

    a("---")
    a("### Appendix: raw signals")
    a("<details><summary>Gathered signal bundle</summary>")
    a("")
    a("```json")
    a(bundle.model_dump_json(indent=2))
    a("```")
    a("</details>")
    a("")
    a("_Generated by the AI SRE agent. Confidence reflects signal quality; a "
      "human on-call should confirm before destructive remediation._")
    return "\n".join(lines)
