---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"   # everything else depends on these
spec:
  project: platform
  source:
    repoURL: "https://github.com/monik1422/sre-platform.git"
    targetRevision: main
    path: platform/namespaces
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {prune: true, selfHeal: true}
